### ISSUE TITLE
pretrain_key

### ISSUE THREAD

**Issue by TomLuijts** [maxwellsh/DIGDriver#1]
Hello,

I'm trying to run the DigDriver.py elementDriver using the [Digestive tract tumors bed file](http://cb.csail.mit.edu/cb/DIG/downloads/mutation_maps/Digestive_tract_tumors_SNV_MNV_INDEL_msi_low.Pretrained.h5) and the [UTR5 with splice annotation bed file](http://cb.csail.mit.edu/cb/DIG/downloads/annotions/noncoding/grch37.canonical_5utr_with_splice.bed). According to the help page of the command, I should specify a 'pretrain_key' (Name of key used to strore pretrained model). What should I fill in for this input argument? I assume this 'key' is known if I would pretrain the model myself but I'm using the pretrained model that is provided trough the [data portal](http://cb.csail.mit.edu/cb/DIG/downloads/).

I'm sorry if this is explained somewhere in [a relevant Wiki section](https://github.com/maxwellsh/DIGDriver/wiki/04:-Overview-of-testing-selection#interval-driver-model) but I couldn't find it.

kind regards,
Tom

**Comment by maxwellsh** [comment]
Hi Tom,
Thanks for the question! The wiki section you're looking for is [here](https://github.com/maxwellsh/DIGDriver/wiki/05:-Analyzing-existing-annotations#interval-driver-model). You'll see there example commands with the relevant `pretrain_key` specified as the third argument. The `pretain_key` your after is `utr5_w_splice` (second example).

Thanks for pointing out this confusion with the documentation. I'm adding a table now listing the available keys and what they are used for.

Please let me know if you run into any additional problems.

Best,
Max

**Comment by TomLuijts** [comment]
Hi Max,

Thanks for the reply. As you suggested, using `utr5_w_splice` as pretrain key solved the issue.

kind regards,
Tom
