### ISSUE TITLE
Documentation Uncertainties

### ISSUE THREAD

**Issue by DarioS** [maxwellsh/DIGDriver#2]
> ... test for positive selection anywhere in the genome in **any cohort** of sequenced tumor samples.

Does that even include cohorts which are not any of the 37 PCAWG cancer types?

> **Genic Model**
> ... Details are provided here (LINK).
> **Elements Model**
> ... Details are provided here (LINK).
> **Sites Model**
> ... Details are provided here (LINK).

What should the links be to?

> You will need the following files from our [data portal](http://cb.csail.mit.edu/cb/DIG/downloads/dig_data_files/):
hg19.fasta or an equivalent hg19 reference fasta file.

What if the user has BAM files aligned to hg38?

> `DigDriver.py` geneDriver Analyzes 19,210 autosomal genes for burdens of mutations in the following categories: synonymous SNVs, missense SNVs, nonsense (stop-gained) SNVs, canonical splice SNVs, truncating SNVs (nonsense & canonical splice), nonsynonymous SNVs (missense, nonsense, & canonical splice), and indels.

How about lncRNA?

**Comment by maxwellsh** [comment]
Hi Dario,
Thanks for the questions. See responses below.

> Does that even include cohorts which are not any of the 37 PCAWG cancer types?

Technically, Dig could be used for cohorts which are not any of the 37 pretrained models. This should be done with caution though, as the pretrained models capture the mutational patterns of that particular cancer type. This can lead to spurious results if the target cancer is quite different than the pretrained model cancer. Can you tell me what types of cancer you are working on? Happy to advise on the right choice of model.

> What should the links be to?

The link you quoted should redirect to http://cb.csail.mit.edu/cb/DIG/downloads/dig_data_files/ from where you can download `hg19.fasta` and `hg19.fasta.fai`.

> What if the user has BAM files aligned to hg38?

Once you've called mutations from hg38, you can use a [liftover tool](https://genome.ucsc.edu/cgi-bin/hgLiftOver) to convert the coordinates to hg19. Then use these hg19 coordinates with Dig!

> How about lncRNA?

You can run the model using the `PCAWG_all_elts` element model. See the first example on our wiki [here](https://github.com/maxwellsh/DIGDriver/wiki/05:-Analyzing-existing-annotations#interval-driver-model). This model includes all of the lncRNAs compiled by [Rheinbay et al. 2020 Nature](https://www.nature.com/articles/s41586-020-1965-x). You can view the bed file of these annotations as a flat text file [here](https://cb.csail.mit.edu/cb/DIG/downloads/annotions/noncoding/grch37.PCAWG_noncoding.bed).

**Comment by DarioS** [comment]
We are examining cutaneous squamous cell carcinoma, which is a sunlight damage skin cancer. One more thought; have you considered creating an interactive web server such that a user could upload a dozen VCFs and obtain predictions, for instance?

**Comment by maxwellsh** [comment]
The melanoma mutation map should work fairly well for cutaneous squamous cell carcinoma. A note of caution when dealing with  cancers with UV-light mutational processes: UV damage can lead to [local hypermutation at transcription factor binding sites](https://www.nature.com/articles/nature17661) in the promoters of highly expressed genes. Its quite hard to model these local hypermutation processes given current data sizes, so Dig often reports mutational burdens in these regions. There is very low likelihood that these hits represent true positive selection.

We'd love to offer this service. We currently don't have the compute resources to host it on our server, though. Maybe in the future, though!
